import L from 'leaflet';

// Map of normalized retailer names → website domains for BrandFetch CDN
export const RETAILER_DOMAINS = {
  'att': 'att.com',
  'at&t': 'att.com',
  'aarons': 'aarons.com',
  "aaron's": 'aarons.com',
  'anytime fitness': 'anytimefitness.com',
  "arby's": 'arbys.com',
  'arbys': 'arbys.com',
  'bp': 'bp.com',
  'barnes & noble': 'barnesandnoble.com',
  'barnes and noble': 'barnesandnoble.com',
  'big lots': 'biglots.com',
  'bob evans': 'bobevans.com',
  'bob evans restaurant': 'bobevans.com',
  'buffalo wild wings': 'buffalowildwings.com',
  'burger king': 'bk.com',
  'chase': 'chase.com',
  'chase bank': 'chase.com',
  'jpmorgan chase': 'chase.com',
  'the cheesecake factory': 'thecheesecakefactory.com',
  'cheesecake factory': 'thecheesecakefactory.com',
  'cracker barrel': 'crackerbarrel.com',
  'cracker barrel old country store': 'crackerbarrel.com',
  'cricket wireless': 'cricketwireless.com',
  'dairy queen': 'dairyqueen.com',
  "denny's": 'dennys.com',
  'dennys': 'dennys.com',
  'dollar general': 'dollargeneral.com',
  'dg market': 'dollargeneral.com',
  'dollar tree': 'dollartree.com',
  "domino's": 'dominos.com',
  "domino's pizza": 'dominos.com',
  'dominos': 'dominos.com',
  'family dollar': 'familydollar.com',
  'fifth third bank': '53.com',
  'first national bank': 'fnb-online.com',
  'first watch': 'firstwatch.com',
  'five guys': 'fiveguys.com',
  "gabe's": 'gabes.com',
  'gabes': 'gabes.com',
  'goodwill': 'goodwill.org',
  'h&r block': 'hrblock.com',
  'hr block': 'hrblock.com',
  'harbor freight': 'harborfreight.com',
  'harbor freight tools': 'harborfreight.com',
  'hobby lobby': 'hobbylobby.com',
  'home depot': 'homedepot.com',
  'the home depot': 'homedepot.com',
  'huntington bank': 'huntington.com',
  'ihop': 'ihop.com',
  "jimmy john's": 'jimmyjohns.com',
  'jimmy johns': 'jimmyjohns.com',
  "kohl's": 'kohls.com',
  'kohls': 'kohls.com',
  'kroger': 'kroger.com',
  'la fitness': 'lafitness.com',
  "lowe's": 'lowes.com',
  "lowe's home improvement": 'lowes.com',
  'lowes': 'lowes.com',
  'marshalls': 'marshalls.com',
  "moe's southwest grill": 'moes.com',
  'moes grill': 'moes.com',
  "ollie's bargain outlet": 'ollies.us',
  'ollies': 'ollies.us',
  'pnc': 'pnc.com',
  'pnc bank': 'pnc.com',
  'panda express': 'pandaexpress.com',
  'panera bread': 'panerabread.com',
  'panera': 'panerabread.com',
  "papa john's": 'papajohns.com',
  'papa johns': 'papajohns.com',
  'pep boys': 'pepboys.com',
  'pizza hut': 'pizzahut.com',
  'planet fitness': 'planetfitness.com',
  'primanti bros': 'primantibros.com',
  "primanti brothers": 'primantibros.com',
  "primanti bros.": 'primantibros.com',
  'qdoba': 'qdoba.com',
  'qdoba mexican eats': 'qdoba.com',
  'qdoba mexican grill': 'qdoba.com',
  'rei': 'rei.com',
  'red robin': 'redrobin.com',
  'red robin gourmet burgers': 'redrobin.com',
  'rite aid': 'riteaid.com',
  'rural king': 'ruralking.com',
  "sam's club": 'samsclub.com',
  'sams club': 'samsclub.com',
  'shop n save': 'shopnsave.us',
  "shop 'n save": 'shopnsave.us',
  'state farm': 'statefarm.com',
  "steak 'n shake": 'steaknshake.com',
  'steak n shake': 'steaknshake.com',
  'subway': 'subway.com',
  'sunoco': 'sunoco.com',
  'tj maxx': 'tjmaxx.com',
  't.j. maxx': 'tjmaxx.com',
  'taco bell': 'tacobell.com',
  'target': 'target.com',
  'texas roadhouse': 'texasroadhouse.com',
  'tim hortons': 'timhortons.com',
  'tractor supply': 'tractorsupply.com',
  'tractor supply co.': 'tractorsupply.com',
  'tractor supply company': 'tractorsupply.com',
  'urban air': 'urbanair.com',
  'urban outfitters': 'urbanoutfitters.com',
  'verizon': 'verizon.com',
  'verizon wireless': 'verizon.com',
  'walgreens': 'walgreens.com',
  'walmart': 'walmart.com',
  'walmart supercenter': 'walmart.com',
  'walmart neighborhood market': 'walmart.com',
  'white castle': 'whitecastle.com',
  'american freight': 'americanfreight.com',
  "einstein bros. bagels": 'einsteinbros.com',
  'einstein bros bagels': 'einsteinbros.com',
  'bealls outlet': 'beallsoutlet.com',
  "dunham's sports": 'dunhamssports.com',
  'dunhams sports': 'dunhamssports.com',
  "sportsman's warehouse": 'sportsmans.com',
  'sportsmans warehouse': 'sportsmans.com',
  'rent-a-center': 'rentacenter.com',
  'smokey bones': 'smokeybones.com',
  'upmc': 'upmc.com',
  'napa auto parts': 'napaonline.com',
  'napa': 'napaonline.com',
  "o'reilly auto parts": 'oreillyauto.com',
  'oreilly auto parts': 'oreillyauto.com',
  "dunkin'": 'dunkindonuts.com',
  'dunkin': 'dunkindonuts.com',
  "dunkin' donuts": 'dunkindonuts.com',
  'dunkin donuts': 'dunkindonuts.com',
  'sheetz': 'sheetz.com',
  'sherwin-williams': 'sherwin-williams.com',
  'sherwin williams': 'sherwin-williams.com',
  'salvation army': 'salvationarmy.org',
  'the salvation army': 'salvationarmy.org',
  'true value': 'truevalue.com',
  'true value of latrobe': 'truevalue.com',
  "fox's pizza den": 'foxspizza.com',
  'foxs pizza den': 'foxspizza.com',
  "fox's pizza": 'foxspizza.com',
  'foxs pizza': 'foxspizza.com',
  "mcdonald's": 'mcdonalds.com',
  'mcdonalds': 'mcdonalds.com',
  '7-eleven': '7-eleven.com',
  '7 eleven': '7-eleven.com',
  'kfc': 'kfc.com',
  'kentucky fried chicken': 'kfc.com',
  "wendy's": 'wendys.com',
  'wendys': 'wendys.com',
  'starbucks': 'starbucks.com',
  'starbucks coffee': 'starbucks.com',
  'cvs': 'cvs.com',
  'cvs pharmacy': 'cvs.com',
  'cvs health': 'cvs.com',
  'aldi': 'aldi.us',
  'giant eagle': 'gianteagle.com',
  'giant eagle supermarket': 'gianteagle.com',
  "jersey mike's": 'jerseymikes.com',
  'jersey mikes': 'jerseymikes.com',
  "jersey mike's subs": 'jerseymikes.com',
  'petsmart': 'petsmart.com',
  'advance auto parts': 'advanceautoparts.com',
  'circle k': 'circlek.com',
  'sonic': 'sonicdrivein.com',
  'sonic drive-in': 'sonicdrivein.com',
  'getgo': 'getgocafe.com',
  'get go': 'getgocafe.com',
  'petco': 'petco.com',
  'chick-fil-a': 'chick-fil-a.com',
  'chickfila': 'chick-fil-a.com',
  'chipotle': 'chipotle.com',
  'chipotle mexican grill': 'chipotle.com',
  "applebee's": 'applebees.com',
  'applebees': 'applebees.com',
  'olive garden': 'olivegarden.com',
  "popeyes": 'popeyes.com',
  "popeye's": 'popeyes.com',
  'popeyes louisiana kitchen': 'popeyes.com',
  'autozone': 'autozone.com',
  'auto zone': 'autozone.com',
  'pet supplies plus': 'petsuppliesplus.com',
  'speedway': 'speedway.com',
  'valvoline': 'valvoline.com',
  'valvoline instant oil change': 'valvoline.com',
  'citizens bank': 'citizensbank.com',
  'citizens': 'citizensbank.com',
  'family dollar / dollar tree': 'familydollar.com',
  'family dollar/dollar tree': 'familydollar.com',
  // Hotels & lodging
  'best western plus': 'bestwestern.com',
  'best western': 'bestwestern.com',
  'cambria hotels': 'choicehotels.com',
  'cambria hotel': 'choicehotels.com',
  'candlewood suites': 'ihg.com',
  'clarion inn': 'choicehotels.com',
  'comfort inn': 'choicehotels.com',
  'comfort inn & suites': 'choicehotels.com',
  'courtyard by marriott': 'marriott.com',
  'courtyard marriott': 'marriott.com',
  'doubletree by hilton': 'hilton.com',
  'doubletree': 'hilton.com',
  'even hotel': 'ihg.com',
  'extended stay america': 'extendedstayamerica.com',
  'extended stay america select suites': 'extendedstayamerica.com',
  'hampton inn & suites': 'hilton.com',
  'hampton inn': 'hilton.com',
  'hilton garden inn': 'hilton.com',
  'home2 suites by hilton': 'hilton.com',
  'home2 suites': 'hilton.com',
  'marriott': 'marriott.com',
  'omni hotel': 'omnihotels.com',
  'omni': 'omnihotels.com',
  'quality inn': 'choicehotels.com',
  'quality inn & suites': 'choicehotels.com',
  'red roof inn': 'redroof.com',
  'residence inn by marriott': 'marriott.com',
  'residence inn': 'marriott.com',
  'staybridge suites': 'ihg.com',
  'towneplace suites by marriott': 'marriott.com',
  'towneplace suites': 'marriott.com',
  'wingate by wyndham': 'wyndhamhotels.com',
  // Local/regional restaurants & businesses
  'bravo cucina italiana': 'bravoitalian.com',
  'bravo': 'bravoitalian.com',
  'brighton hot dog shoppe': 'brightonhotdogshoppe.com',
  'burgatory': 'burgatory.com',
  'busy beaver': 'busybeaver.com',
  'busy beaver building centers': 'busybeaver.com',
  'commonplace coffee': 'commonplacecoffee.com',
  'duquesne university': 'duq.edu',
  'fnb financial center': 'fnb-online.com',
  'fnb': 'fnb-online.com',
  'first national bank financial center': 'fnb-online.com',
  'hofbrauhaus': 'hofbrauhauspittsburgh.com',
  'hofbrauhaus pittsburgh': 'hofbrauhauspittsburgh.com',
  "jason's deli": 'jasonsdeli.com',
  'jasons deli': 'jasonsdeli.com',
  "jeni's ice cream": 'jenis.com',
  "jeni's splendid ice creams": 'jenis.com',
  'jenis ice cream': 'jenis.com',
  'juniper grill': 'junipergrill.com',
  'kura sushi': 'kurasushi.com',
  'mad mex': 'madmex.com',
  'nextier bank': 'nextierbank.com',
  'ppg paints arena': 'ppgpaintsarena.com',
  'pins mechanical': 'pinsmechanical.com',
  'pins mechanical co': 'pinsmechanical.com',
};

// Fallback: local logo files for brands BrandFetch may not cover well
export const LOGO_FILES = {
  'att': 'ATT.png',
  'at&t': 'ATT.png',
  'aarons': 'Aarons.png',
  "aaron's": 'Aarons.png',
  'ace hardware': 'Ace Hardware.png',
  'anytime fitness': 'Anytime Fitness.png',
  "arby's": 'Arbys.png',
  'arbys': 'Arbys.png',
  'bank of america': 'Bank of America.png',
  'bath & body works': 'Bath and Body Works.png',
  'bath and body works': 'Bath and Body Works.png',
  'best buy': 'Best Buy.png',
  'bp': 'BP.png',
  'barnes & noble': 'Barnes and Noble.png',
  'barnes and noble': 'Barnes and Noble.png',
  'big lots': 'Big Lots.png',
  'bob evans': 'Bob Evans.png',
  'bob evans restaurant': 'Bob Evans.png',
  'buffalo wild wings': 'Buffalo Wild Wings.png',
  'burger king': 'Burger King.png',
  'chase': 'Chase Bank.png',
  'chase bank': 'Chase Bank.png',
  'jpmorgan chase': 'Chase Bank.png',
  'the cheesecake factory': 'Cheesecake Factory.png',
  'cheesecake factory': 'Cheesecake Factory.png',
  "chili's": 'Chilis.png',
  'chilis': 'Chilis.png',
  'capital one': 'Capital One.png',
  'capital one bank': 'Capital One.png',
  'costco': 'Costco.png',
  'costco wholesale': 'Costco.png',
  'cracker barrel': 'Cracker Barrel.png',
  "culver's": 'Culvers.png',
  'culvers': 'Culvers.png',
  'cracker barrel old country store': 'Cracker Barrel.png',
  'cricket wireless': 'Cricket Wireless.png',
  'dairy queen': 'Dairy Queen.png',
  "denny's": 'Dennys.png',
  'dennys': 'Dennys.png',
  "dick's sporting goods": 'Dicks Sporting Goods.png',
  'dicks sporting goods': 'Dicks Sporting Goods.png',
  'discount tire': 'Discount Tire.png',
  'dollar general': 'Dollar General.png',
  'dg market': 'DG Market.png',
  'dollar tree': 'Dollar Tree.png',
  "domino's": 'Dominos.png',
  "domino's pizza": 'Dominos.png',
  'dominos': 'Dominos.png',
  'family dollar': 'Family Dollar.png',
  'fifth third bank': 'Fifth Third Bank.png',
  'first national bank': 'First National Bank.png',
  'first watch': 'First Watch.png',
  'five below': 'Five Below.png',
  'five guys': 'Five Guys.png',
  'firehouse subs': 'Firehouse Subs.png',
  'firestone': 'Firestone.png',
  'firestone complete auto care': 'Firestone.png',
  'foot locker': 'Foot Locker.png',
  "gabe's": 'Gabes.png',
  'gabes': 'Gabes.png',
  'gamestop': 'GameStop.png',
  'gnc': 'GNC.png',
  'goodwill': 'Goodwill.png',
  'goodyear': 'Goodyear.png',
  'goodyear auto service': 'Goodyear.png',
  'h&r block': 'HR Block.png',
  'hr block': 'HR Block.png',
  'harbor freight': 'Harbor Freight.png',
  'harbor freight tools': 'Harbor Freight.png',
  'hobby lobby': 'Hobby Lobby.png',
  'home depot': 'Home Depot.png',
  'the home depot': 'Home Depot.png',
  'huntington bank': 'Huntington Bank.png',
  'ihop': 'IHOP.png',
  'jiffy lube': 'Jiffy Lube.png',
  "jimmy john's": 'Jimmy Johns.png',
  'jimmy johns': 'Jimmy Johns.png',
  'keybank': 'KeyBank.png',
  'key bank': 'KeyBank.png',
  "kohl's": 'Kohls.png',
  'kohls': 'Kohls.png',
  'kroger': 'Kroger.png',
  'la fitness': 'LA Fitness.png',
  'little caesars': 'Little Caesars.png',
  "little caesar's": 'Little Caesars.png',
  "lowe's": 'Lowes.png',
  "lowe's home improvement": 'Lowes.png',
  'lowes': 'Lowes.png',
  "macy's": 'Macys.png',
  'macys': 'Macys.png',
  'marathon': 'Marathon.png',
  'marathon gas': 'Marathon.png',
  'marshalls': 'Marshalls.png',
  'meineke': 'Meineke.png',
  'meineke car care': 'Meineke.png',
  'michaels': 'Michaels.png',
  'midas': 'Midas.png',
  "moe's southwest grill": 'Moes Grill.png',
  'moes grill': 'Moes Grill.png',
  'office depot': 'Office Depot.png',
  'officemax': 'Office Depot.png',
  'old navy': 'Old Navy.png',
  "ollie's bargain outlet": 'Ollies.png',
  'ollies': 'Ollies.png',
  'outback steakhouse': 'Outback Steakhouse.png',
  'outback': 'Outback Steakhouse.png',
  'pnc': 'PNC.png',
  'pnc bank': 'PNC.png',
  'panda express': 'Panda Express.png',
  'panera bread': 'Panera Bread.png',
  'panera': 'Panera Bread.png',
  "papa john's": 'Papa Johns.png',
  'papa johns': 'Papa Johns.png',
  'pep boys': 'Pep Boys.png',
  'pizza hut': 'Pizza Hut.png',
  'planet fitness': 'Planet Fitness.png',
  'primanti bros': 'Primanti Bros.png',
  "primanti brothers": 'Primanti Bros.png',
  "primanti bros.": 'Primanti Bros.png',
  'qdoba': 'Qdoba.png',
  'qdoba mexican eats': 'Qdoba.png',
  'qdoba mexican grill': 'Qdoba.png',
  'regions bank': 'Regions Bank.png',
  'regions': 'Regions Bank.png',
  'rei': 'REI.png',
  'red robin': 'Red Robin.png',
  'red robin gourmet burgers': 'Red Robin.png',
  'rite aid': 'Rite Aid.png',
  'rural king': 'Rural King.png',
  "sam's club": 'Sams Club.png',
  'sams club': 'Sams Club.png',
  'sephora': 'Sephora.png',
  'shell': 'Shell.png',
  'shell gas': 'Shell.png',
  'shop n save': 'Shop n Save.png',
  "shop 'n save": 'Shop n Save.png',
  'staples': 'Staples.png',
  'state farm': 'State Farm.png',
  "steak 'n shake": 'Steak n Shake.png',
  'steak n shake': 'Steak n Shake.png',
  'subway': 'Subway.png',
  'sunoco': 'Sunoco.png',
  't-mobile': 'T-Mobile.png',
  'tmobile': 'T-Mobile.png',
  'tj maxx': 'TJ Maxx.png',
  "trader joe's": 'Trader Joes.png',
  'trader joes': 'Trader Joes.png',
  't.j. maxx': 'TJ Maxx.png',
  'taco bell': 'Taco Bell.png',
  'target': 'Target.png',
  'texas roadhouse': 'Texas Roadhouse.png',
  'tim hortons': 'Tim Hortons.png',
  'tractor supply': 'Tractor Supply Company.png',
  'tractor supply co.': 'Tractor Supply Company.png',
  'tractor supply company': 'Tractor Supply Company.png',
  'urban air': 'Urban Air.png',
  'urban outfitters': 'Urban Outfitters.png',
  'us bank': 'US Bank.png',
  'u.s. bank': 'US Bank.png',
  'verizon': 'Verizon.png',
  'verizon wireless': 'Verizon.png',
  'walgreens': 'Walgreens.png',
  'walmart': 'Walmart.png',
  'walmart supercenter': 'Walmart.png',
  'walmart neighborhood market': 'Walmart.png',
  'wells fargo': 'Wells Fargo.png',
  'wells fargo bank': 'Wells Fargo.png',
  'white castle': 'White Castle.png',
  'whole foods': 'Whole Foods.png',
  'whole foods market': 'Whole Foods.png',
  'wingstop': 'Wingstop.png',
  "zaxby's": 'Zaxbys.png',
  'zaxbys': 'Zaxbys.png',
  'american freight': 'American Freight.png',
  "einstein bros. bagels": 'Einstein Bros Bagels.png',
  'einstein bros bagels': 'Einstein Bros Bagels.png',
  'bealls outlet': 'Bealls Outlet.png',
  "dunham's sports": 'Dunhams Sports.png',
  'dunhams sports': 'Dunhams Sports.png',
  "sportsman's warehouse": 'Sportsmans Warehouse.png',
  'sportsmans warehouse': 'Sportsmans Warehouse.png',
  'rent-a-center': 'Rent-A-Center.png',
  'smokey bones': 'Smokey Bones.png',
  'upmc': 'UPMC.png',
  'napa auto parts': 'NAPA Auto Parts.png',
  'napa': 'NAPA Auto Parts.png',
  "o'reilly auto parts": 'OReilly Auto Parts.png',
  'oreilly auto parts': 'OReilly Auto Parts.png',
  "dunkin'": 'Dunkin.png',
  'dunkin': 'Dunkin.png',
  "dunkin' donuts": 'Dunkin.png',
  'dunkin donuts': 'Dunkin.png',
  'sheetz': 'Sheetz.png',
  'sherwin-williams': 'Sherwin-Williams.png',
  'sherwin williams': 'Sherwin-Williams.png',
  'salvation army': 'Salvation Army.png',
  'the salvation army': 'Salvation Army.png',
  'true value': 'True Value.png',
  'true value of latrobe': 'True Value.png',
  "fox's pizza den": 'Foxs Pizza.png',
  'foxs pizza den': 'Foxs Pizza.png',
  "fox's pizza": 'Foxs Pizza.png',
  'foxs pizza': 'Foxs Pizza.png',
  // ── Additional major brands ──
  "mcdonald's": 'McDonalds.png',
  'mcdonalds': 'McDonalds.png',
  '7-eleven': '7-Eleven.png',
  '7 eleven': '7-Eleven.png',
  'kfc': 'KFC.png',
  'kentucky fried chicken': 'KFC.png',
  "wendy's": 'Wendys.png',
  'wendys': 'Wendys.png',
  'starbucks': 'Starbucks.png',
  'starbucks coffee': 'Starbucks.png',
  'cvs': 'CVS.png',
  'cvs pharmacy': 'CVS.png',
  'cvs health': 'CVS.png',
  'aldi': 'ALDI.png',
  'giant eagle': 'Giant Eagle.png',
  'giant eagle supermarket': 'Giant Eagle.png',
  "jersey mike's": 'Jersey Mikes.png',
  'jersey mikes': 'Jersey Mikes.png',
  "jersey mike's subs": 'Jersey Mikes.png',
  'petsmart': 'PetSmart.png',
  'advance auto parts': 'Advance Auto Parts.png',
  'circle k': 'Circle K.png',
  'sonic': 'Sonic.png',
  'sonic drive-in': 'Sonic.png',
  'getgo': 'GetGo.png',
  'get go': 'GetGo.png',
  'petco': 'Petco.png',
  'chick-fil-a': 'Chick-fil-A.png',
  'chickfila': 'Chick-fil-A.png',
  'chipotle': 'Chipotle.png',
  'chipotle mexican grill': 'Chipotle.png',
  "applebee's": 'Applebees.png',
  'applebees': 'Applebees.png',
  'olive garden': 'Olive Garden.png',
  "popeyes": 'Popeyes.png',
  "popeye's": 'Popeyes.png',
  'popeyes louisiana kitchen': 'Popeyes.png',
  // ── Additional unmapped brands ──
  'autozone': 'AutoZone.png',
  'auto zone': 'AutoZone.png',
  'pet supplies plus': 'Pet Supplies Plus.png',
  'speedway': 'Speedway.png',
  'valvoline': 'Valvoline.png',
  'valvoline instant oil change': 'Valvoline.png',
  'citizens bank': 'Citizens Bank.png',
  'citizens': 'Citizens Bank.png',
  'family dollar / dollar tree': 'Family Dollar Dollar Tree.png',
  'family dollar/dollar tree': 'Family Dollar Dollar Tree.png',
  // Hotels & lodging
  'best western plus': 'Best Western Plus.png',
  'best western': 'Best Western Plus.png',
  'cambria hotels': 'Cambria Hotels.png',
  'cambria hotel': 'Cambria Hotels.png',
  'candlewood suites': 'Candlewood Suites.png',
  'clarion inn': 'Clarion Inn.png',
  'comfort inn': 'Comfort Inn.png',
  'comfort inn & suites': 'Comfort Inn.png',
  'courtyard by marriott': 'Courtyard by Marriott.png',
  'courtyard marriott': 'Courtyard by Marriott.png',
  'doubletree by hilton': 'DoubleTree by Hilton.png',
  'doubletree': 'DoubleTree by Hilton.png',
  'even hotel': 'Even Hotel.png',
  'extended stay america': 'Extended Stay America Select Suites.png',
  'extended stay america select suites': 'Extended Stay America Select Suites.png',
  'hampton inn & suites': 'Hampton Inn & Suites.png',
  'hampton inn': 'Hampton Inn & Suites.png',
  'hilton garden inn': 'Hilton Garden Inn.png',
  'home2 suites by hilton': 'Home2 Suites by Hilton.png',
  'home2 suites': 'Home2 Suites by Hilton.png',
  'marriott': 'Marriott.png',
  'omni hotel': 'Omni Hotel.png',
  'omni': 'Omni Hotel.png',
  'premier suites': 'Premier Suites.png',
  'quality inn': 'Quality Inn.png',
  'quality inn & suites': 'Quality Inn.png',
  'red roof inn': 'Red Roof Inn.png',
  'residence inn by marriott': 'Residence Inn by Marriott.png',
  'residence inn': 'Residence Inn by Marriott.png',
  'staybridge suites': 'Staybridge Suites.png',
  'towneplace suites by marriott': 'TownePlace Suites by Marriott.png',
  'towneplace suites': 'TownePlace Suites by Marriott.png',
  'wingate by wyndham': 'Wingate by Wyndham.png',
  // Local/regional restaurants & businesses
  'bravo cucina italiana': 'Bravo Cucina Italiana.png',
  'bravo': 'Bravo Cucina Italiana.png',
  'brighton hot dog shoppe': 'Brighton Hot Dog Shoppe.png',
  'burgatory': 'Burgatory.png',
  'busy beaver': 'Busy Beaver.png',
  'busy beaver building centers': 'Busy Beaver.png',
  'china wok': 'China Wok.png',
  'commonplace coffee': 'Commonplace Coffee.png',
  'duquesne university': 'Duquesne University.png',
  'fnb financial center': 'FNB Financial Center.png',
  'fnb': 'FNB Financial Center.png',
  'first national bank financial center': 'FNB Financial Center.png',
  'hofbrauhaus': 'Hofbrauhaus.png',
  'hofbrauhaus pittsburgh': 'Hofbrauhaus.png',
  "jason's deli": 'Jasons Deli.png',
  'jasons deli': 'Jasons Deli.png',
  "jeni's ice cream": 'Jenis Ice Cream.png',
  "jeni's splendid ice creams": 'Jenis Ice Cream.png',
  'jenis ice cream': 'Jenis Ice Cream.png',
  'juniper grill': 'Juniper Grill.png',
  'kura sushi': 'Kura Sushi.png',
  'mad mex': 'Mad Mex.png',
  'nextier bank': 'NexTier Bank.png',
  'over the bar': 'Over the Bar.png',
  'over the bar bicycle cafe': 'Over the Bar.png',
  'ppg paints arena': 'PPG Paints Arena.png',
  'patron mexican grill': 'Patron Mexican Grill.png',
  'pins mechanical': 'Pins Mechanical.png',
  'pins mechanical co': 'Pins Mechanical.png',
  'pizza bosa': 'Pizza Bosa.png',
  "pizza joe's": 'Pizza Joes.png',
  'pizza joes': 'Pizza Joes.png',
  'pizza milano': 'Pizza Milano.png',
  'saga hibachi': 'Saga Hibachi.png',
  'sakura japanese steakhouse': 'Sakura Japanese Steakhouse.png',
  'sakura': 'Sakura Japanese Steakhouse.png',
  "salem's": 'Salems.png',
  'salems': 'Salems.png',
  "salem's market": 'Salems.png',
  'speckled egg': 'Speckled Egg.png',
  'the speckled egg': 'Speckled Egg.png',
  'tepache': 'Tepache.png',
  'waffles incaffeinated': 'Waffles INCaffeinated.png',
};

// Resolve a retailer name to a domain (for BrandFetch) and/or local file
export function _resolveName(normalized) {
  // Direct match
  let domain = RETAILER_DOMAINS[normalized];
  let file = LOGO_FILES[normalized];
  if (domain || file) return { domain, file };
  // Prefix/substring fallback
  for (const [key, d] of Object.entries(RETAILER_DOMAINS)) {
    if (normalized.startsWith(key) || key.startsWith(normalized)) {
      domain = d;
      break;
    }
  }
  for (const [key, f] of Object.entries(LOGO_FILES)) {
    if (normalized.startsWith(key) || key.startsWith(normalized)) {
      file = f;
      break;
    }
  }
  return { domain, file };
}

export function getLogoUrl(retailerName) {
  const normalized = retailerName.toLowerCase().trim();
  const { domain, file } = _resolveName(normalized);
  if (!domain && !file) return null;
  const localUrl = file ? `/logos/${file}` : null;
  // Local logos (212+ PNGs) as primary — reliable, no API dependency
  // BrandFetch proxy at /api/logo/:domain available as fallback
  // (requires registered domain origin to return real images)
  const brandfetchUrl = domain ? `/api/logo/${domain}` : null;
  return localUrl || brandfetchUrl;
}

// Get BrandFetch proxy fallback URL for onerror handling (when local logo fails)
export function getFallbackLogoUrl(retailerName) {
  const normalized = retailerName.toLowerCase().trim();
  const { domain } = _resolveName(normalized);
  return domain ? `/api/logo/${domain}` : null;
}

export const LOGO_H = 46; // Fixed height for all logo markers
export const LOGO_MIN_W = 36; // Minimum width (narrow/square logos)
export const LOGO_MAX_W = 150; // Maximum width — auto-expand for wide wordmarks (Dunkin', Subway, etc.)

// Cache of logo natural dimensions: url → { w, h, aspect }
export const logoDimCache = {};

export function preloadLogo(url) {
  if (logoDimCache[url]) return Promise.resolve(logoDimCache[url]);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const aspect = img.naturalWidth / img.naturalHeight;
      logoDimCache[url] = { w: img.naturalWidth, h: img.naturalHeight, aspect };
      resolve(logoDimCache[url]);
    };
    img.onerror = () => {
      logoDimCache[url] = { w: 1, h: 1, aspect: 1 };
      resolve(logoDimCache[url]);
    };
    img.src = url;
  });
}

// Get marker width for a logo based on its natural aspect ratio
export function getLogoMarkerW(logoUrl) {
  const cached = logoDimCache[logoUrl];
  if (!cached) return LOGO_MIN_W;
  // Scale width to maintain aspect ratio at fixed height
  const innerH = LOGO_H - 19; // padding (8px×2) + border (1.5px×2) overhead
  const naturalW = innerH * cached.aspect + 19; // add back padding + border
  return Math.max(LOGO_MIN_W, Math.min(LOGO_MAX_W, Math.round(naturalW)));
}

export function createLogoIcon(logoUrl, retailerName) {
  const markerW = getLogoMarkerW(logoUrl);
  // Inner dimensions after padding (8px) and border (1.5px) on each side
  const innerW = markerW - 19;
  const innerH = LOGO_H - 19;

  // Build onerror: try BrandFetch fallback (since local is primary now), then hide
  const fallback = retailerName ? getFallbackLogoUrl(retailerName) : null;
  const onerror = fallback
    ? `this.onerror=function(){this.style.display='none'};this.src='${fallback}'`
    : "this.style.display='none'";

  return L.divIcon({
    html: `<div class="logo-marker" style="width:${markerW}px;height:${LOGO_H}px;"><img src="${logoUrl}" alt="" width="${innerW}" height="${innerH}" style="object-fit:contain;" onerror="${onerror}" /></div>`,
    className: '',
    iconSize: [markerW, LOGO_H],
    iconAnchor: [markerW / 2, LOGO_H / 2],
    popupAnchor: [0, -LOGO_H / 2],
  });
}
